---

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: "yes"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: 'docker'

- name: Install docker package
  apt:
    name: docker-ce
    state: installed
