---

- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: kubeadm, tags: kubeadm }

#- hosts: master
#  gather_facts: no
#  become: yes
#  roles:
#    - { role: kubernetes/master, tags: master }
#
#- hosts: node
#  gather_facts: no
#  become: yes
#  roles:
#    - { role: kubernetes/node, tags: node }
#
#- hosts: master
#  gather_facts: no
#  become: yes
#  roles:
#    - { role: cni, tags: cni }
#    - { role: addon, tags: addon }
