---

- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: kubeadm, tags: kubeadm }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: k8smaster, tags: master }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: k8snode, tags: node }
